### ISSUE TITLE
Report bugs

### ISSUE THREAD

**Issue by QingyangZhang** [duchengbin8/Stable_Diffusion_is_Unstable#2]
Awesome work! I tried to replace the original file at conda/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py with m_clip.py. However, there are some bugs. For example, at line 714 of m_clip.py, inputs_embeds[-1] should be inputs_shape[-1]. Besides, after fixing aforementioned bugs, I still cannot reproduce the original results in the paper. Could the authors provide more details on how to modify the source code in 'transformer' library?

**Comment by duchengbin8** [comment]
What results cannot be reproduced? Adversarial prompt or FID?

**Comment by QingyangZhang** [comment]
> What results cannot be reproduced? Adversarial prompt or FID?

Just fail to run up the code. In m_clip.py, you modify the original class CLIPTextTransformer to accept input in the form of 'text_embeds'. However, in line 226 of whitebox_attack.py and line 743 of m_clip.py, it still needs "input_ids" to get "pooled_output". This results in a NoneType error. I try to fix this by assuming the last token is "end of sequence (eos)" token. This is my solution:

        if input_ids is not None:
            pooled_output = last_hidden_state[
                torch.arange(last_hidden_state.shape[0], device=last_hidden_state.device),
                input_ids.to(dtype=torch.int, device=last_hidden_state.device).argmax(dim=-1),
            ]
        elif inputs_embeds is not None:
            pooled_output = last_hidden_state[
                torch.arange(last_hidden_state.shape[0], device=last_hidden_state.device),
                input_shape[1]-1,
            ]

I am not sure if this implementation is right. Could you please share more ideas about how to fix this? Thanks a lot.

**Comment by duchengbin8** [comment]
Is your transformers==4.28.1？

**Comment by QingyangZhang** [comment]
Yes, I believe I strictly follow the guidance in Readme.

**Comment by duchengbin8** [comment]
I updated the m_clip file, I uploaded the wrong file before, sorry for the trouble. It should work properly now.

**Comment by QingyangZhang** [comment]
> I updated the m_clip file, I uploaded the wrong file before, sorry for the trouble. It should work properly now.

Thanks for the very timely reply, but the problem remains. Now I can run the code. But in the main loop, CLIP classifier frequently misclassifies the generated images. The code always "skip this text" at line 163. However, CLIP zero-shot classification accuracy is about 70% in ImageNet-1K. There should not be so many misclassified images. I try to visualize the generated images. They seem unnatural. It seems that there is something wrong with the stable diffusion generation at line 157. I also try to generate images by directly input a text string, it will generate natural images. So I think it is because of the input prompt_embeds.
![aaa](https://github.com/duchengbin8/Stable_Diffusion_is_Unstable/assets/52411664/7f21996d-81fe-4736-80b6-ed4c34833dea)

**Comment by duchengbin8** [comment]
In config.py, change the img_size to 512

**Comment by QingyangZhang** [comment]
Thanks for your help. It works now.
